# -*- mode: ruby -*-
source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'therubyracer', platforms: :ruby
gem 'haml-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'
gem 'capistrano-rails', group: :development
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'twitter_bootstrap_form_for', github: 'tamouse/twitter_bootstrap_form_for'
gem 'annotate', '~> 2.6.5'
gem 'sidekiq'
gem 'money-rails'
gem 'sinatra', require: nil
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'html2haml'
  gem 'foreman'
  gem 'mailcatcher'
  gem 'guard'
  gem 'guard-rspec'
end
